### ISSUE TITLE
success insert commute information(arrival(출근), leave(퇴근)) . but, not insert date info..

### ISSUE THREAD

**Issue by Choe-Ji-Hwan** [2021-2-SWEngineering-SoTree/SoTree-POS-FrontEnd#57]
1. 
success insert commute information(arrival(출근), leave(퇴근)) to database . 
but, not insert date info.. why..?
I got a code 
`const date = new Date(+new Date() + 3240 * 10000).toISOString().replace("T", " ").replace(/\..*/, '')`
and assign `commingTime`. but not insert date info.

2.
last employee info isn't inserted database.

**Comment by hojunlee-hj** [comment]
해결했습니다~
